language: python
group: travis_latest
dist: xenial

sudo: false
matrix:
  include:
  - python: "3.7"
    env: NUMPY_VERSION="1.16.6"
  - python: "3.7"
    env: NUMPY_VERSION="1.21.0"
  - python: "3.8"
    env: NUMPY_VERSION="1.16.6"
  - python: "3.8"
    env: NUMPY_VERSION="1.17.5"
  - python: "3.8"
    env: NUMPY_VERSION="1.18.5"
  - python: "3.8"
    env: NUMPY_VERSION="1.19.5"
  - python: "3.8"
    env: NUMPY_VERSION="1.20.3"
  - python: "3.8"
    env: NUMPY_VERSION="1.21.0"
  - python: "3.9"
    env: NUMPY_VERSION="1.16.6"
  - python: "3.9"
    env: NUMPY_VERSION="1.17.5"
  - python: "3.9"
    env: NUMPY_VERSION="1.18.5"
  - python: "3.9"
    env: NUMPY_VERSION="1.19.5"
  - python: "3.9"
    env: NUMPY_VERSION="1.20.3"
  - python: "3.9"
    env: NUMPY_VERSION="1.21.0"

before_install:
  - pip install "numpy==$NUMPY_VERSION"
install:
  - python setup.py install
script:
  - python setup.py test
  - python -m doctest README.rst
notifications:
  email: false
